#!/bin/bash

# Define the name of the project
PROJECT_NAME="verilog_test_case"

# Define the list of Verilog files to be included in the project
VERILOG_FILES=()
assignments=()

while IFS=  read -r -d $'\0'; do
    assignments+=("$REPLY")
done < <(find . -name "Assignment*" -print0)

for i in ${!assignments[@]}; do
    cd "${assignments[$i]}"
    pwd

    array=()
    while IFS=  read -r -d $'\0'; do
        array+=("$REPLY")
    done < <(find . -name "*tb.v" -print0)

    echo "element $i is ${array[$i]}"
    VERILOG_FILES="${array[$i]}"

    #echo "${array}"
    echo "${VERILOG_FILES}"
    
    # Compile the Verilog files into an executable
    iverilog -o $PROJECT_NAME "$VERILOG_FILES"
    
    # Run the simulation for scripts
    vvp $PROJECT_NAME
    cd ..
done
# Print a message indicating that the script has finished running
echo "Success! Script has finished running."
