#!/bin/bash

# Define the name of the project
PROJECT_NAME="verilog_test_case"

# Define the list of Verilog files to be included in the project
VERILOG_FILES=()
while IFS=  read -r -d $'\0'; do
    VERILOG_FILES+=("$REPLY")
done < <(find . -name "*tb.v" -print0)

for i in ${!VERILOG_FILES[@]}; do
  echo "element $i is ${VERILOG_FILES[$i]}"
done


# Compile the Verilog files into an executable
iverilog -o $PROJECT_NAME $VERILOG_FILES

# Run the simulation for scripts
vvp $PROJECT_NAME

# Print a message indicating that the script has finished running
echo "Success! Script has finished running."
