name: Verilog Build and Analysis

on: [push, pull_request]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Verilog Compiler
      uses: jge162/verilog_compiler@1.0.0

    - run: |
        echo "Install required dependencies"
        sudo apt-get update
        sudo apt-get install iverilog
        sudo apt-get install verilator

    - run: |
        echo "Set executable permission on script file"
        chmod +x script/sh
        files = $(find . -name "*tb.v")
        echo "$files"
        # chmod +x *tb.v
        
    - run: |
        echo "Run, Build Application using script"
        ./script/sh
